In [60]:
import numpy as np

## single dimensional array

In [61]:
sda = np.array([12, 21, 31, 41, 51])
sda

array([12, 21, 31, 41, 51])

In [62]:
type(sda)

numpy.ndarray

## multi dimensional array

In [63]:
mda = np.array([[12, 21, 31, 41, 51], [1, 5, 8, 9, 3]])
mda

array([[12, 21, 31, 41, 51],
       [ 1,  5,  8,  9,  3]])

In [64]:
type(mda)

numpy.ndarray

## initialize numpy array

In [65]:
ina = np.zeros((1, 2))
ina

array([[0., 0.]])

In [66]:
ina = np.zeros((7, 7))
ina

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [67]:
ina = np.full((10, 10), 10)
ina

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [68]:
ina = np.arange(1, 30)
ina

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [69]:
ina = np.arange(1, 300, 5)
ina

array([  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,
        66,  71,  76,  81,  86,  91,  96, 101, 106, 111, 116, 121, 126,
       131, 136, 141, 146, 151, 156, 161, 166, 171, 176, 181, 186, 191,
       196, 201, 206, 211, 216, 221, 226, 231, 236, 241, 246, 251, 256,
       261, 266, 271, 276, 281, 286, 291, 296])

In [70]:
irn = np.random.randint(1, 100, 5)
irn

array([ 9, 71, 86, 40, 74])

In [71]:
irn = np.random.randint(100, 11000, 10)
irn

array([ 8152,  3018,  7024,  4570, 10409,  4093,  2896,  2234,  8395,
        6335])

## check the shape of numpy array

In [72]:
csna = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 11]])
csna.shape

(2, 5)

In [73]:
csna.shape = (5, 2)

In [74]:
csna

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 11]])

In [79]:
csna.shape = (10, 1)

In [80]:
csna

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [11]])

## joining numpy arrays