In [103]:
import numpy as np

# single dimensional array

In [104]:
sda = np.array([12, 21, 31, 41, 51])
sda

array([12, 21, 31, 41, 51])

In [105]:
type(sda)

numpy.ndarray

# multi dimensional array

In [106]:
mda = np.array([[12, 21, 31, 41, 51], [1, 5, 8, 9, 3]])
mda

array([[12, 21, 31, 41, 51],
       [ 1,  5,  8,  9,  3]])

In [107]:
type(mda)

numpy.ndarray

# initialize numpy array

In [108]:
ina = np.zeros((1, 2))
ina

array([[0., 0.]])

In [109]:
ina = np.zeros((7, 7))
ina

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [110]:
ina = np.full((10, 10), 10)
ina

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [111]:
ina = np.arange(1, 30)
ina

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [112]:
ina = np.arange(1, 300, 5)
ina

array([  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,
        66,  71,  76,  81,  86,  91,  96, 101, 106, 111, 116, 121, 126,
       131, 136, 141, 146, 151, 156, 161, 166, 171, 176, 181, 186, 191,
       196, 201, 206, 211, 216, 221, 226, 231, 236, 241, 246, 251, 256,
       261, 266, 271, 276, 281, 286, 291, 296])

In [113]:
irn = np.random.randint(1, 100, 5)
irn

array([82, 81, 36, 40, 16])

In [114]:
irn = np.random.randint(100, 11000, 10)
irn

array([ 617,  868, 4499, 5147, 5033, 5302, 7696, 1731, 3403,  213])

# check the shape of numpy array

In [115]:
csna = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 11]])
csna.shape

(2, 5)

In [116]:
csna.shape = (5, 2)

In [117]:
csna

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 11]])

In [118]:
csna.shape = (10, 1)

In [119]:
csna

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [11]])

# joining numpy arrays

### vstack

In [120]:
n1 = np.array([11, 22, 33, 44, 55])

In [121]:
n2 = np.array([15, 25, 35, 45, 60])

In [122]:
np.vstack((n1, n2))

array([[11, 22, 33, 44, 55],
       [15, 25, 35, 45, 60]])

### hstack

In [123]:
np.hstack((n1, n2))

array([11, 22, 33, 44, 55, 15, 25, 35, 45, 60])

### column_stack

In [124]:
np.column_stack((n1, n2))

array([[11, 15],
       [22, 25],
       [33, 35],
       [44, 45],
       [55, 60]])

# Intersection And Difference

In [125]:
n1 = np.array([10, 20, 30, 40, 50, 60])

In [126]:
n2 = np.array([50, 60, 70, 80, 90])

In [127]:
np.intersect1d(n1, n2)

array([50, 60])

In [128]:
np.setdiff1d(n1, n2)

array([10, 20, 30, 40])

In [129]:
np.setdiff1d(n2, n1)

array([70, 80, 90])

# Array Mathematics

### Addition Of Numpy Arrays

In [130]:
n1 = np.array([10, 20])

In [131]:
n2 = np.array([30, 40])

In [132]:
np.sum([n1, n2])

100

In [133]:
np.sum([n1, n2], axis = 0)

array([40, 60])

In [134]:
np.sum([n1, n2], axis = 1)

array([30, 70])

### Basic Addition

In [135]:
 n1 = np.array([10, 20, 30])

In [136]:
n1 = n1 + 1
n1

array([11, 21, 31])

### Basic Subtraction

In [137]:
 n1 = np.array([10, 20, 30])

In [138]:
n1 = n1 - 1
n1

array([ 9, 19, 29])

### Basic Multiplication

In [139]:
 n1 = np.array([10, 20, 30])

In [143]:
n1 = n1 * 2
n1

array([ 40,  80, 120])

### Basic Division

In [144]:
 n1 = np.array([10, 20, 30])

In [145]:
n1 = n1 / 2
n1

array([ 5., 10., 15.])

# Math Functions

### Mean

In [146]:
n1 = np.array([10, 20, 30, 40, 50, 60])

In [147]:
np.mean(n1)

35.0

### Median

In [151]:
n2 = np.array([11, 22, 33, 44, 55, 66])

In [152]:
np.median(n2)

38.5

### Standard Divitions

In [153]:
n3 = np.array([91, 81, 71, 61, 51, 41])

In [154]:
np.std(n3)

17.07825127659933