In [21]:
import numpy as np

# single dimensional array

In [22]:
sda = np.array([12, 21, 31, 41, 51])
sda

array([12, 21, 31, 41, 51])

In [23]:
type(sda)

numpy.ndarray

# multi dimensional array

In [24]:
mda = np.array([[12, 21, 31, 41, 51], [1, 5, 8, 9, 3]])
mda

array([[12, 21, 31, 41, 51],
       [ 1,  5,  8,  9,  3]])

In [25]:
type(mda)

numpy.ndarray

# initialize numpy array

In [26]:
ina = np.zeros((1, 2))
ina

array([[0., 0.]])

In [27]:
ina = np.zeros((7, 7))
ina

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [28]:
ina = np.full((10, 10), 10)
ina

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [29]:
ina = np.arange(1, 30)
ina

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
ina = np.arange(1, 300, 5)
ina

array([  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,
        66,  71,  76,  81,  86,  91,  96, 101, 106, 111, 116, 121, 126,
       131, 136, 141, 146, 151, 156, 161, 166, 171, 176, 181, 186, 191,
       196, 201, 206, 211, 216, 221, 226, 231, 236, 241, 246, 251, 256,
       261, 266, 271, 276, 281, 286, 291, 296])

In [31]:
irn = np.random.randint(1, 100, 5)
irn

array([90, 28, 94, 82, 64])

In [32]:
irn = np.random.randint(100, 11000, 10)
irn

array([5853, 3089, 4198, 5385, 5322, 1939, 8534, 8130, 3634, 2334])

# check the shape of numpy array

In [33]:
csna = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 11]])
csna.shape

(2, 5)

In [34]:
csna.shape = (5, 2)

In [35]:
csna

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 11]])

In [36]:
csna.shape = (10, 1)

In [37]:
csna

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [11]])

# joining numpy arrays

### vstack

In [38]:
n1 = np.array([11, 22, 33, 44, 55])

In [39]:
n2 = np.array([15, 25, 35, 45, 60])

In [40]:
np.vstack((n1, n2))

array([[11, 22, 33, 44, 55],
       [15, 25, 35, 45, 60]])

### hstack

In [42]:
np.hstack((n1, n2))

array([11, 22, 33, 44, 55, 15, 25, 35, 45, 60])

### column_stack

In [43]:
np.column_stack((n1, n2))

array([[11, 15],
       [22, 25],
       [33, 35],
       [44, 45],
       [55, 60]])

# Intersection And Difference

In [44]:
n1 = np.array([10, 20, 30, 40, 50, 60])

In [45]:
n2 = np.array([50, 60, 70, 80, 90])

In [46]:
np.intersect1d(n1, n2)

array([50, 60])

In [47]:
np.setdiff1d(n1, n2)

array([10, 20, 30, 40])

In [48]:
np.setdiff1d(n2, n1)

array([70, 80, 90])

# Array Mathematics

### Addition Of Numpy Arrays